extends:
  - 'standard'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
settings:
  react:
    version: detect
globals:
  localStorage: true
  location: true
rules:
  camelcase: off
